<?php include "header.phtml"; ?>
<h2 class='text-center py-3'>Welcome, <span><?= $usernameSession['name']; ?> </span>!</h2>

<div class="main">


    <?php foreach ($posts as $key => $post) : ?>
        <div class="container">
            <div class="card">

                <div class="card-title">
                    <h3 class=""><?= htmlspecialchars($post['title']); ?></h3>
                    <p>Added </span> on <span><small><?= htmlspecialchars($post['created_at']); ?></small></span></p>
                </div>

                <div class="card-body">
                    <div class="buttons">
                        <p class="lead "><?= htmlspecialchars($post['body']); ?></p>
                        <a href="post.php?post=<?= htmlspecialchars($post['id']); ?>" class="btn-dark">More</a>
                        <a href="edit.php?post=<?= htmlspecialchars($post['id']); ?>" class="btn-dark">Edit</a>

                        <a href="dashboard.php?del=<?= htmlspecialchars(intval($post['id'])) ?>" class="btn-danger" type="submit">Delete</a>
                    </div>

                        <img src="uploads/<?= $value['img_url']; ?>" alt="">

                </div>


            </div>
        </div>
        <hr>
    <?php endforeach; ?>
</div>
<?php include "footer.phtml"; ?>