<?php include "header.phtml"; ?>
<div class="main">
    <div class="container">
        <form action="edit.php?post=<?= htmlspecialchars($post['postId']); ?>" method="post" class="add-post" enctype="multipart/form-data">
            <h1 class="text-center">Edit your post here</h1>

            <div class="form-control">
                <label for="title">Title : </label>
                <input type="text" name="title" value="<?=htmlspecialchars( $post['title']); ?>">
            </div>

            <div class="form-control">
                <label for="content">Content : </label>
                <textarea name="content" id="" cols="30" rows="10"><?= htmlspecialchars($post['body']); ?></textarea>
            </div>

            <div class="form-control ">
                <label for="file" class="custom-file-label">Chose File</label>
                <input type="file" name="file" class="" id="file" accept="image/png, image/jpeg" multiple value="<?= $post['img']; ?>">
                <img src="uploads/<?= $post['img']; ?>" alt="No img" class="thumbnail">
            </div>



            <input class="btn mb-2 py-2" type="submit" name="add-post" value="Edit post">

        </form>
    </div>
</div>
<?php include "footer.phtml"; ?>