<?php include "db.php";
?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Le Pire Coin </title>
</head>

<body>
    <nav>
        <ul>
            <div class="logo">
                <li>
                    <a href="./">Le Pire Coin</a>
                </li>
            </div>
            <div class="links">
                <?php if (!isset($_SESSION['logged'])) : ?>
                    <li>
                        <a href="register.php">Register</a>
                    </li>
                    <li>
                        <a href="login.php">Login</a>
                    </li>
                <?php else : ?>
                    <li>
                        <a href="add.php">Add Post</a>
                    </li>
                    <li>
                        <a href="dashboard.php">Dashboard</a>
                    </li>
                    <li>
                        <a href="logout.php?logout">Logout</a>
                    </li>
                <?php endif; ?>
            </div>

        </ul>
    </nav>