<h1 class="text-center mb-5 py-5">Here are the latest posts</h1>

<div class="main">
    <?php foreach ($posts as $key => $post) : ?>
        <div class="container">
            <div class="card">

                <div class="card-title">
                    <h3 class=""><?= $post['title']; ?></h3>
                    <p>Added </span> on <span><small><?= $post['created_at']; ?></small></span> by <?= $post['name']; ?></p>
                </div>

                <div class="card-body">
                    <div class="buttons">
                        <!-- <a href="" class="btn-dark">Read More</a> -->
                        <a href="post.php?post=<?= $post['postId']; ?>" class=" btn-dark">More</a>

                        <p class="lead "><?= $post['body']; ?></p>
                    </div>
                    <img src="uploads/<?= $post['img']; ?>" alt="">
                </div>


            </div>
        </div>
        <hr>
    <?php endforeach; ?>
</div>