<?php include "header.phtml"; ?>


<section class="text-gray-500 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="-my-8">

            <?php foreach ($posts as  $post) : ?>
                <div class="justify-between mx-auto py-8 flex border-t-2 border-gray-800 flex-wrap md:flex-no-wrap">
                    <div class=" md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                        <span class="tracking-widest font-medium title-font text-white">CATEGORY</span>
                        <span class="mt-1 text-gray-600 text-sm"><?= $post['postCreated'] ?></span>
                        <a class="block relative h-48 rounded overflow-hidden">
                            <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/421x261">
                        </a>
                    </div>
                    <div class="flex-col flex content-between justify-between">
                        <h2 class="text-2xl font-medium text-white title-font mb-2"><?= $post['title'] ?></h2>
                        <p class="leading-relaxed"><?= $post['body'] ?></p>
                        <a class="text-green-500 inline-flex items-center mt-4">Learn More
                            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M5 12h14"></path>
                                <path d="M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>
                <!-- 
                <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                    <a class="block relative h-48 rounded overflow-hidden">
                        <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/421x261">
                    </a>
                    <div class="mt-4">
                        <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                        <h2 class="text-gray-900 title-font text-lg font-medium">Shooting Stars</h2>
                        <p class="mt-1">$21.15</p>
                    </div>
                </div> -->
            <?php endforeach; ?>

        </div>
    </div>
</section>

<?php include "footer.phtml"; ?>